import streamlit as st
import mysql.connector
import pandas as pd
from fpdf import FPDF
import datetime

# 1. PLATFORM CONFIGURATION
st.set_page_config(page_title="Sleowl AI Engine", page_icon="🦉", layout="wide")

st.markdown("""
    <style>
    .stApp { background-color: #0e1117; color: #00ffcc; }
    h1, h2, h3 { color: #00ffcc !important; font-family: 'Courier New'; }
    .stButton>button { 
        background: linear-gradient(45deg, #ff00ff, #00ffff); 
        color: white; border-radius: 12px; border: none; font-weight: bold; height: 3.5em; width: 100%;
    }
    .footer {
        position: fixed; left: 0; bottom: 0; width: 100%;
        background-color: #1a1c24; color: #00ffcc; text-align: center;
        padding: 10px; font-family: 'Courier New'; font-size: 14px;
        border-top: 1px solid #ff00ff;
    }
    </style>
    """, unsafe_allow_html=True)

# 2. THE DYNAMIC "AI" ASSEMBLY ENGINE
def synthesize_sleowl_prescription(name, w, h, bmi, ex, state, mental):
    # Intro string
    report = f"### 🧬 Sleowl Bio-Kinetic Diagnostic for {name}\n"
    report += f"**System Telemetry:** Weight: {w}kg | Height: {h}cm | BMI: {bmi}\n\n"
    
    # --- MODULE 1: MORPHOLOGY & DIET ---
    report += "#### 🥦 1. Nutritional Vector (Strict Vegetarian)\n"
    if bmi < 18.5:
        report += f"With a BMI of {bmi} (Underweight), your system requires a caloric surplus. "
        report += "Prescription: 2500+ kcal vegetarian diet. High intake of paneer, lentils (dal), and nut butters to fuel mass generation.\n\n"
    elif 18.5 <= bmi <= 24.9:
        report += f"With a BMI of {bmi} (Optimal), your mass-to-height ratio is in the peak physiological zone. "
        report += "Prescription: Maintenance calories. Focus on complex carbs and lean plant proteins (tofu, mung beans) to sustain energy.\n\n"
    else:
        report += f"With a BMI of {bmi} (Elevated), we are detecting excess tissue mass. "
        report += "Prescription: Caloric deficit protocol. Strict adherence to high-fiber greens, completely avoiding processed sugars. Emphasize hydration.\n\n"

    # --- MODULE 2: KINETIC OUTPUT ---
    report += "#### ⚙️ 2. Kinetic Protocol\n"
    if ex < 3:
        report += f"Your current output of {ex} hours/week is below the optimal threshold. "
        if state in ["Fatigued", "Injured"]:
            report += f"However, given your '{state}' physical state, this low output is protective. Focus entirely on mobility and stretching this week.\n\n"
        else:
            report += "Gradually increase cardiovascular training. Target 4-5 hours weekly to optimize your VO2 Max for high-focus aviation scenarios.\n\n"
    elif 3 <= ex <= 6:
        report += f"Your kinetic output of {ex} hours/week is perfectly aligned with standard athletic maintenance. "
        report += f"Since you are in a '{state}' state, continue your trajectory with a focus on progressive overload and core stability.\n\n"
    else:
        report += f"High kinetic output detected ({ex} hours/week). "
        report += "Warning: Monitor for overtraining. Ensure you are consuming enough complex vegetarian proteins to repair muscle tissue at this volume.\n\n"

    # --- MODULE 3: MENTAL STATE ---
    report += "#### 🧠 3. Cognitive & Neural Recovery\n"
    if mental <= 4:
        report += f"Alert: Neural fatigue detected (Score: {mental}/10). "
        report += "Cognitive processing will be compromised. Action: Enforce 8.5+ hours of sleep, digital detox 1 hour before bed, and deep breathing protocols.\n"
    elif 5 <= mental <= 7:
        report += f"Neural energy is stable (Score: {mental}/10). "
        report += "You have the bandwidth for moderate-to-high focus tasks. Maintain current sleep hygiene and utilize 4-4-4-4 box breathing to sustain your edge.\n"
    else:
        report += f"Peak neural charge confirmed (Score: {mental}/10). "
        report += "You are in an optimal flow state. Capitalize on this by tackling complex problem-solving or high-level strategic planning.\n"

    report += "\n---\n*Prescription generated by the Sleowl Offline AI Matrix.*"
    return report

# 3. PDF GENERATOR
def create_report(user_name, plan, bmi):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 18)
    pdf.cell(0, 15, "Sleowl Clinical Diagnostic Report", ln=True, align='C')
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Patient Name: {user_name} | System BMI: {bmi}", ln=True)
    pdf.ln(10)
    clean_plan = plan.replace('*', '').replace('#', '')
    pdf.multi_cell(0, 8, clean_plan)
    return pdf.output(dest='S').encode('latin-1')

# 4. ADMIN SECURITY
with st.sidebar:
    st.header("🔐 Admin Vault")
    db_pass = st.text_input("Aiven MySQL Password", type="password")

if not db_pass:
    st.warning("SYSTEM OFFLINE: Enter MySQL password to initialize.")
    st.stop()

# 5. DIAGNOSTIC PORTAL
st.title("🦉 SLEOWL: BIO-KINETIC ENGINE")
st.markdown("---")

col1, col2 = st.columns([3, 2], gap="large")

with col1:
    st.subheader("📋 Subject Telemetry Form")
    with st.form("main_form"):
        name = st.text_input("Subject Identification (Name)")
        c1, c2 = st.columns(2)
        with c1:
            w = st.number_input("Mass (kg)", min_value=1.0, value=85.0)
            ex = st.number_input("Kinetic Output (Hrs/Week)", min_value=0, value=3)
        with c2:
            h = st.number_input("Height (cm)", min_value=1.0, value=180.0)
            state = st.selectbox("Current Physiology", ["Peak", "Normal", "Fatigued", "Injured"])
        mental = st.slider("Cognitive Energy Score", 1, 10, 5)
        submitted = st.form_submit_button("INITIALIZE SLEOWL DIAGNOSTIC")

    if submitted:
        bmi = round(w / ((h/100)**2), 2)
        
        # INSTANT GENERATION - NO API CALLS
        plan_text = synthesize_sleowl_prescription(name, w, h, bmi, ex, state, mental)
        
        st.success("Diagnostic Synthesized Instantly.")
        st.markdown(plan_text)

        report_bytes = create_report(name, plan_text, bmi)
        st.download_button(label="📥 DOWNLOAD OFFICIAL PDF REPORT", data=report_bytes, file_name=f"Sleowl_{name}.pdf", mime="application/pdf")

        # Database Sync
        try:
            conn = mysql.connector.connect(host='sleowl-ind-sleowl-db.k.aivencloud.com', user='avnadmin', password=db_pass, port='15618', database='defaultdb')
            cursor = conn.cursor()
            cursor.execute("CREATE TABLE IF NOT EXISTS public_diagnostics (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), bmi FLOAT, plan TEXT)")
            cursor.execute("INSERT INTO public_diagnostics (name, bmi, plan) VALUES (%s, %s, %s)", (name, bmi, plan_text))
            conn.commit()
            conn.close()
            st.toast("Telemetry securely synced to Aiven Cloud.")
        except Exception as e:
            st.error(f"Cloud Database Fault: {e}")

with col2:
    st.subheader("🌍 Enterprise Analytics")
    if st.checkbox("Initialize Global Telemetry"):
        try:
            conn = mysql.connector.connect(host='sleowl-ind-sleowl-db.k.aivencloud.com', user='avnadmin', password=db_pass, port='15618', database='defaultdb')
            df = pd.read_sql("SELECT bmi FROM public_diagnostics", conn)
            st.metric("Total Diagnostics Processed", len(df))
            st.line_chart(df['bmi'])
            conn.close()
        except:
            st.info("Establishing secure connection to Aiven Cloud...")

st.markdown(f'<div class="footer"><p>Built with ❤️ by Devansh Nadpara | Powered by Sleowl Proprietary Engine 🦉</p></div>', unsafe_allow_html=True)
